### ISSUE TITLE
Замечания по index.html

### ISSUE THREAD

**Issue by mishaberezin** [smirnovvy/smirnovvy.github.io#3]
* Заменить табы на четыре пробела
* Добавить кодировку (`<meta charset...`)
* [Инлайновые стили](https://github.com/smirnovvy/smirnovvy.github.io/blob/a937bf14e617e1e3dadc8ec8106ea155a6d4a8bb/index.html#L8) перенести в index.css. Стили применить через css-класс.

В остальном ок.

**Comment by smirnovvy** [comment]
Будет исправлено в рамках #4
