### ISSUE TITLE
Добавить конвертер валют

### ISSUE THREAD

**Issue by mishaberezin** [smirnovvy/smirnovvy.github.io#8]
По аналогии со страницей `/math.html` нужно добавить страницу `/curcon.html`, на которой будет расположен конвертер валют.

Конвертер должен представлять из себя два текстовых инпута `<input type='text'>` и два соответствующих селекта `<select>`. С помощью селектов можно выбрать валюты, между которыми происходит конвертация. В инпутах вводится и выводится значение.
Конвертация происходит непосредственно по мере ввода, т.е. кнопки «посчитать» не будет.

Будем использовать три валюты: Доллары, Евро, Рубли.

Изучать:
- [Элемент select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)
- [Событие `change`](https://developer.mozilla.org/en-US/docs/Web/Events/change)
- [Событие `input`](https://developer.mozilla.org/en-US/docs/Web/Events/input)

Работать должно примерно так:
- https://www.google.ru/search?q=currency+converter
- https://yandex.ru/search/?text=%D0%BA%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82%D0%B5%D1%80%20%D0%B2%D0%B0%D0%BB%D1%8E%D1%82

**Comment by smirnovvy** [comment]
https://github.com/smirnovvy/smirnovvy.github.io/pull/9
